<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="3" hostname="bb-system-3161" failures="1" tests="1" name="Test" time="17.388" errors="0" timestamp="2023-03-20T23:05:58 IST">
  <testcase classname="com.appTests.SignUpTest" name="validateSignUp" time="12.722">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.appTests.SignUpTest.validateSignUp(SignUpTest.java:28)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- validateSignUp -->
  <testcase classname="com.appTests.CheckoutItemToCart" name="validateCheckout" time="0.0">
    <ignored/>
  </testcase> <!-- validateCheckout -->
  <testcase classname="com.appTests.BaseTest" name="@BeforeSuite beforeSuite" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite beforeSuite -->
  <testcase classname="com.appTests.BaseTest" name="@AfterSuite afterSuite" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterSuite afterSuite -->
</testsuite> <!-- Test -->
